### ISSUE TITLE
Phonegap still not working - any idea why?

### ISSUE THREAD

**Issue by harspeck** [artemisoftnian/com-artemisoftnian-plugins-unityads2#2]
First, thanks so much for working on this - UnityAds seems like a really solid ad route to take. 

I saw that this issue was closed, but not resolved. Still, maybe you might be able to help out...

I receive this error when I try to build using Phonegap (it's the exact same error as previously reported):

Error - Plugin error (you probably need to remove plugin files from your app): //github.com/artemisoftnian/com-artemisoftnian-plugins-unityads2 --nohooks=.": Fetching plugin "https://github.com/artemisoftnian/com-artemisoftnian-plugins-unityads2" via git clone Using shallow clone Repository "https://github.com/artemisoftnian/com-artemisoftnian-plugins-unityads2" checked out to git ref "master" at "9dcbff3". Installing "com-artemisoftnian-plugins-unityads2" at "0.0.1" for android Error during processing of action! Attempting to revert... Failed to install 'com-artemisoftnian-plugins-unityads2': CordovaError: Uh oh! Destination "/libs/classes.jar" for source file "/tmp/gimlet/12798280/3150099/www_android/project/cordova/plugins/com-artemisoftnian-plugins-unityads2/src/android/libs/classes.jar" is located outside the project at copyFile (/tmp/gimlet/12798280/3150099/www_android/project/cordova/lib/pluginHandlers.js:231:15) at install (/tmp/gimlet/12798280/3150099/www_android/project/cordova/lib/pluginHandlers.js:74:13) at Object.process (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25) at PluginManager.doOperation (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20) at PluginManager.addPlugin (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17) at /tmp/gimlet/12798280/3150099/www_android/project/cordova/Api.js:254:18 at _fulfilled (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/q/q.js:834:54) at self.promiseDispatch.done (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/q/q.js:863:30) at Promise.promise.promiseDispatch (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/q/q.js:796:13) at /tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/q/q.js:556:49 Uh oh! Destination "/libs/classes.jar" for source file "/tmp/gimlet/12798280/3150099/www_android/project/cordova/plugins/com-artemisoftnian-plugins-unityads2/src/android/libs/classes.jar" is located outside the project

I have a few ideas of what could be causing it, but mostly just some questions:

Any reason it's referencing 0.0.1 and not 2.2.1? 
Phonegap uses plugman to compile - could this be the problem? It seems like Phonegap isn't able to find files, but your directory tree seems to fit the specs for plugman compilation. Maybe something I'm missing?

**Comment by creakosta** [comment]
it would be cool if the developer fix this error.

**Comment by artemisoftnian** [comment]
Hi, I'm aware of the problem, At the moment of the code creation the "add swift support" plugin doesn't worked on PGB because it doesn't support hooks.  As soon as I can I will be looking into the problem again too see if the "add swift support" plugin have already fix this.

**Comment by mahdi71** [comment]
is there no way to fix this ?
